# Generated by Django 3.0.5 on 2020-05-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hlp_otherprivateckey_paillierprivateckey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealBFVPrivatecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_key', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'BFV私钥',
            },
        ),
        migrations.CreateModel(
            name='SealCKKSPrivatecKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_key', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CKKS私钥',
            },
        ),
    ]
