# Generated by Django 3.0.5 on 2020-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hlp_otherpublickey_paillierpublickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SealBFVPublicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('relin_keys', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'BFV公钥',
            },
        ),
        migrations.CreateModel(
            name='SealCKKSPublicKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_key', models.TextField()),
                ('relin_keys', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'CKKS公钥',
            },
        ),
    ]
