# Generated by Django 3.0.5 on 2020-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sealbfvpublickey_sealckkspublickey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linear_Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a1', models.IntegerField()),
                ('a2', models.IntegerField()),
                ('c', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '一次风控模型函数',
            },
        ),
        migrations.CreateModel(
            name='Multiple_Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coefficientArray', models.TextField()),
                ('powerArray', models.TextField()),
                ('lastC', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '多次风控模型函数',
            },
        ),
        migrations.AlterModelOptions(
            name='en_algorithm',
            options={'verbose_name_plural': '风控模型'},
        ),
        migrations.RenameField(
            model_name='en_algorithm',
            old_name='multiply',
            new_name='functionId',
        ),
        migrations.RenameField(
            model_name='en_algorithm',
            old_name='plus',
            new_name='operation',
        ),
        migrations.AddField(
            model_name='en_algorithm',
            name='power',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
